### ISSUE TITLE
install 실행하는 방법

### ISSUE THREAD

**Issue by jisoo03010** [dataignitelab/iot_ai_model#5]
커스텀 데이터로 학습시키려고 하는데 어떻게 하면 되나요?

**Comment by copper-light** [comment]
Renset, Inception 모델에 대한 내용 Notebook 파일이 업로드되었으며, 향후 다른 모델에 대해서 업로드 진행 예정입니다.

**Comment by copper-light** [comment]
각 샘플 코드에 대해서는 노트북 파일로 업로드되었습니다.
